"use client";

import React from "react";
import BottomNav from "../BottomNav";
import { useRouter } from "next/navigation";
import "../globals.css";

export default function Projects() {
  const router = useRouter();
  return (
    <div className="relative px-6 flex justify-center items-center h-[100vh] w-full flex-col">
      <div className="flex flex-col w-full md:max-w-[720px]">
        <h3 className="text-[32px] md:text-[50px] mb-4 font-medium px-2">
          PROJECTS
        </h3>
        <div className="flex flex-col md:gap-2">
          <div
            onClick={() => router.push("/projects/aiart")}
            className="flex gap-2 items-center w-full justify-between cursor-pointer hover:bg-gray-100 px-2 py-3 rounded-md"
          >
            <div className="flex gap-2 items-baseline">
              <span className="text-[#21201c] font-medium">AI Art Gallery</span>
              <span className="text-[#63635e] text-[14px] hidden md:flex">
                A digital gallery with art generated by MidJourney and DALL•E
              </span>
            </div>
            <p className="text-[#63635e] text-[14px]">Present</p>
          </div>
          <div
            onClick={() => router.push("/projects/waves")}
            className="flex gap-2 items-center w-full justify-between cursor-pointer hover:bg-gray-100 px-2 py-3 rounded-md"
          >
            <div className="flex gap-2 items-baseline">
              <span className="font-medium text-[#21201c]">Waves NFT</span>
              <span className="text-[#63635e] text-[14px] hidden md:flex">
                5000 randomly generated sound waves
              </span>
            </div>
            <p className="text-[#63635e] text-[14px]">2021</p>
          </div>
          <div
            onClick={() => router.push("/projects/spline")}
            className="flex gap-2 items-center w-full justify-between cursor-pointer hover:bg-gray-100 px-2 py-3 rounded-md"
          >
            <div className="flex gap-2">
              <span className="font-medium text-[#21201c]">Spline Explorations</span>
              <span className="text-[#63635e] hidden md:flex text-[14px]">
                3D animations created in Spline
              </span>
            </div>
            <p className="text-[#63635e] text-[14px]">Present</p>
          </div>
          <div className="flex gap-2 items-center w-full justify-between cursor-pointer hover:bg-gray-100 px-2 py-3 rounded-md">
            <div className="flex gap-2 items-baseline">
              <span className="font-medium text-[#21201c]">MIM Art Gallery</span>
              <span className="text-[#63635e] hidden md:flex text-[14px]">
                NYC apartment art gallery
              </span>
            </div>
            <p className="text-[#63635e] text-[14px]">COMING SOON</p>
          </div>
        </div>
      </div>
      <div className="flex margin-auto absolute bottom-[15%] md:bottom-[10%] justify-center w-full pt-24">
        <BottomNav />
      </div>
    </div>
  );
}
